graph TD
    A[Board of Directors / Mining Rights Holder] --> B(Chief Executive Officer or General Manager)
    B --> C(Mine Manager)
    C --> D(Assistant Manager / Superintendent)
    D --> E(Mine Captain)
    D --> F(Competent Person)
    C --> G(Electrical Engineer / Electrician)
    C --> H(Mechanical Engineer / Subordinate Engineer)
    C --> I(Chief Surveyor)
    C --> J(Ventilation Engineer)
    E --> K(Shift Boss)
    F --> L(Shift Foreman)
    K --> M
    L --> M

